title: Your awesome title
author: Sam Rubin
email: sjrube32@gmail.com

show_excerpts: false # Set to true to show excepert on the homepage

minima:
  skin: dark
  
  # generate social links
  social_links:
    twitter: lunaarvibes
    github: lunaaar
    linkedin: samuel-rubin-

jekyll-theme-serial-programmer:
  skin: dark

# Build Settings
# theme: minima
remote_theme: jekyll-theme-serial-programmer
